# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Dotnet CI-CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: package
      run: dotnet publish -c Release -o webapp
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: webapp
        path: webapp/**
        
  deploy_dev:
    runs-on: ubuntu-latest
    needs: [build]
    environment: 
      name: dev
      url: https://some.url
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v2.0.8
        with:
          name: webapp
          path: webapp
      - name: Run a one-line script
        run: echo Hello, world!

  deploy_test:
    runs-on: ubuntu-latest
    needs: [deploy_dev]
    environment: test
    steps:
      - name: Run a one-line script
        run: echo Hello, world!

  deploy_prod:
    runs-on: ubuntu-latest
    needs: [deploy_test]
    environment: prod
    steps:
      - name: Run a one-line script
        run: echo Hello, world!
